appName: adservice
appImage: northamerica-northeast2-docker.pkg.dev/ecommerce-platform-automation/inventory-registry/adservice
appVersion: "8034a2a882087c142cd14a560813db37ebc2fbc2"
appReplicas: 2
containerPort: 9555
containerEnvVars: 
- name: PORT
  value: "9555"

servicePort: 9555

serviceAccountNameOverride: "svc-api"
gsaEmail: "svc-api-sa@ecommerce-platform-automation.iam.gserviceaccount.com"
