appName: adservice
appImage: northamerica-northeast2-docker.pkg.dev/ecommerce-platform-automation/inventory-registry/adservice
appVersion: v0.10.0
appReplicas: 2
containerPort: 9555
containerEnvVars: 
- name: PORT
  value: "9555"

servicePort: 9555

serviceAccountNameOverride: "svc-api"
gsaEmail: "svc-api-sa@ecommerce-platform-automation.iam.gserviceaccount.com"
