appName: checkoutservice
appImage: northamerica-northeast2-docker.pkg.dev/ecommerce-platform-automation/inventory-registry/checkoutservice
appVersion: "8034a2a882087c142cd14a560813db37ebc2fbc2"
appReplicas: 2
containerPort: 5050
containerEnvVars: 
  - name: PORT
    value: "5050"
  - name: PRODUCT_CATALOG_SERVICE_ADDR   
    value: "productcatalogservice:3550"
  - name: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - name: PAYMENT_SERVICE_ADDR
    value: "paymentservice:50051"    
  - name: EMAIL_SERVICE_ADDR
    value: "emailservice:5000"
  - name: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - name: CART_SERVICE_ADDR
    value: "cartservice:7070"

servicePort: 5050

serviceAccountNameOverride: "svc-api"
gsaEmail: "svc-api-sa@ecommerce-platform-automation.iam.gserviceaccount.com"
