appName: currencyservice
appImage: northamerica-northeast2-docker.pkg.dev/ecommerce-platform-automation/inventory-registry/currencyservice
appVersion: "8034a2a882087c142cd14a560813db37ebc2fbc2"
appReplicas: 2
containerPort: 7000
containerEnvVars: 
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 7000

serviceAccountNameOverride: "svc-api"
gsaEmail: "svc-api-sa@ecommerce-platform-automation.iam.gserviceaccount.com"
