appName: shippingservice
appImage: northamerica-northeast2-docker.pkg.dev/ecommerce-platform-automation/inventory-registry/shippingservice
appVersion: "8034a2a882087c142cd14a560813db37ebc2fbc2"
appReplicas: 2
containerPort: 50051
containerEnvVars: 
- name: PORT
  value: "50051"

servicePort: 50051

serviceAccountNameOverride: "svc-api"
gsaEmail: "svc-api-sa@ecommerce-platform-automation.iam.gserviceaccount.com"
