appName: shippingservice
appImage: northamerica-northeast2-docker.pkg.dev/ecommerce-platform-automation/inventory-registry/shippingservice
appVersion: v0.10.0
appReplicas: 2
containerPort: 50051
containerEnvVars: 
- name: PORT
  value: "50051"

servicePort: 50051

serviceAccountNameOverride: "svc-api"
gsaEmail: "svc-api-sa@ecommerce-platform-automation.iam.gserviceaccount.com"
