apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emailservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/email-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cartservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/cart-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currencyservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/currency-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paymentservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/payment-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendationservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/recommendation-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productcatalogservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/productcatalog-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shippingservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/shipping-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/ad-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkoutservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/checkout-service-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontendservice
  namespace: argocd
spec:
  destination:
    namespace: ms-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ummahafsahimi/A-Cloude-Native-SaaS-Platform-with-Full-DevOps-Automation.git
    targetRevision: gitOps
    path: charts/microservice
    helm:
      valueFiles:
        - ../../values/frontend-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
