apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountNameOverride | default .Chart.Name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gsaEmail | quote }}

